const zh = {
  common: {
    cancel: '取消', close: '关闭', save: '保存', saveChanges: '保存更改', saving: '保存中…', delete: '删除', deleting: '删除中…', add: '添加', edit: '编辑', clear: '清除', clearAll: '全部清除', search: '搜索', refresh: '刷新', loading: '加载中…', loadMore: '加载更多', selected: '已选择 {{count}} 项', pageOf: '第 {{page}} 页，共 {{total}} 页', pageSize: '每页数量', previousPage: '上一页', nextPage: '下一页', noResults: '未找到结果', name: '名称', description: '描述', members: '成员', projects: '项目', teams: '团队', created: '创建时间', updated: '更新时间', status: '状态', role: '角色', type: '类型', title: '标题', content: '内容', author: '作者', dueDate: '截止日期', priority: '优先级', assignees: '负责人', actions: '操作', info: '信息', owner: '所有者', member: '成员', user: '用户', team: '团队', project: '项目', workItem: '工作项', entry: '条目', relationship: '关系', unknownUser: '未知用户', unknownProject: '未知项目', unknownTeam: '未知团队', notSet: '未设置', notAvailable: '不可用', none: '无', noDueDate: '无截止日期', noPriority: '无优先级', untitledProject: '未命名项目', never: '从未', remove: '移除', previous: '上一页', next: '下一页', show: '显示', hide: '隐藏', password: '密码', email: '邮箱', username: '用户名', timezone: '时区', users: '用户', providers: '提供商', model: '模型', tokens: '令牌', requests: '请求', failures: '失败', successRate: '成功率', projectCount: '{{count}} 个项目', memberCount: '{{count}} 名成员', item: '项', items: '项', there: '这里', yes: '是', no: '否',
  },
  status: {
    open: '开放', inProgress: '进行中', blocked: '受阻', waiting: '等待中', answered: '已回答', pending: '待处理', approved: '已批准', rejected: '已拒绝', done: '已完成', decided: '已决定', cancelled: '已取消', active: '启用', inactive: '停用', revoked: '已撤销', resetRequired: '需要重置', ready: '就绪',
  },
  role: {
    admin: '管理员', user: '用户', owner: '所有者', member: '成员', viewer: '查看者', editor: '编辑者', teamOwner: '团队所有者', teamMember: '团队成员',
  },
  priority: { low: '低', medium: '中', high: '高', urgent: '紧急' },
  workItemType: { note: '备注', task: '任务', question: '问题', approval: '审批', review: '评审', decision: '决策' },
  entryType: { comment: '评论', information: '信息', answer: '回答', evidence: '证据', proposal: '提案', resolution: '解决方案' },
  relationshipType: { blockedBy: '被阻塞于', dependsOn: '依赖于', relatedTo: '相关于', answers: '回答', supports: '支持', contradicts: '矛盾于', resolves: '解决', supersedes: '取代' },
  auth: {
    usernameOrEmail: '用户名或邮箱', signIn: '登录', signingIn: '登录中…', hidePassword: '隐藏密码', showPassword: '显示密码', failedSignIn: '登录失败。', changePassword: '修改密码', newPassword: '新密码', confirmPassword: '确认密码', updatePassword: '更新密码', updating: '更新中…', loadingSession: '正在加载会话…', requiredNewPassword: '请输入新密码。', passwordMinLength: '密码至少需要 6 个字符。', passwordsMismatch: '两次输入的密码不一致。', failedUpdatePassword: '密码更新失败。',
  },
  home: {
    greeting: '早上好，{{name}}', subtitle: '你想完成什么？', askAnything: '问问任何事情…', askAnythingLabel: '随便问问', submitCommand: '提交指令', tryAsking: '试着问问', attention: '什么事情需要我关注？', attentionPrompt: '今天有什么事情需要我关注？', teamHelp: '哪个团队可以帮忙？', teamHelpPrompt: '哪个团队可以帮助处理这个问题？', summarizeProjects: '总结我的项目', summarizeProjectsPrompt: '总结我的项目，并突出显示重要事项。',
  },
  chat: {
    justNow: '刚刚', minutesAgo: '{{count}} 分钟前', hoursAgo: '{{count}} 小时前', daysAgo: '{{count}} 天前', monthsAgo: '{{count}} 个月前', yearsAgo: '{{count}} 年前',
    noConversations: '暂无对话', moreActions: '更多操作', moreActionsFor: '{{title}} 的更多操作', rename: '重命名', renameSession: '重命名会话', sessionName: '会话名称', deleteSession: '删除会话？', deleteSessionDescription: '这将永久删除对话及其中的消息。', failedRename: '重命名聊天会话失败。', failedDelete: '删除聊天会话失败。', failedLoadSessions: '加载聊天会话失败。', failedLoadSession: '加载聊天会话失败。', failedStartSession: '新建聊天会话失败。', startBeforeSending: '请先开始聊天会话再发送消息。', clearContext: '清除已选上下文', stopResponse: '停止响应', sendMessage: '发送消息', recordVoice: '录制语音消息', stopRecording: '停止录音', cancelRecording: '取消录音', recording: '录音中', transcribing: '正在转写…', microphoneNotSupported: '当前浏览器不支持录音。', microphonePermissionPrompt: '浏览器询问录音权限时，请允许访问麦克风。', microphonePermissionDenied: '麦克风访问被拒绝。请在此网站的浏览器设置中允许访问，然后重试，或直接输入消息。', voiceRecordingFailed: '无法开始录音。', voiceTranscriptionFailed: '语音转写失败，请重试。', voiceTranscriptionUnavailable: '语音转写不可用，请先配置语音转写提供商。', noSpeechDetected: '未检测到语音。', chatWithAi: '与 AI 聊天', startNewChat: '开始新聊天', closeChat: '关闭 AI 聊天', greeting: '今天我可以怎样帮助你？', thinking: '思考中…', openReference: '打开{{type}} {{label}}', unresolvedReference: '未解析的引用',
  },
  ask: {
    addContext: '添加上下文', people: '人员', loadingContext: '正在加载上下文…', noMatchingProjects: '没有匹配的项目', noMatchingTeams: '没有匹配的团队', noMatchingPeople: '没有匹配的人员', useAsContext: '将 {{label}} 用作上下文', removeFromContext: '从上下文移除 {{label}}', projectPrefix: '项目：', aiUnavailable: 'AI 不可用', aiUnavailableDescription: '配置 AI 提供商后即可提问和生成内容。', askAi: '询问 AI', failedLoadContext: '加载聊天上下文失败。', failedLoadAsk: '加载 Ask 失败。', failedLoadProjectContext: '加载项目上下文失败。', maxProjects: '最多可添加 {{count}} 个项目作为上下文。', failedUpdateContext: '更新上下文失败。', failedClearContext: '清除上下文失败。', failedRefreshSessions: '刷新聊天会话失败。', failedAddWorkItem: '添加工作项上下文失败。', failedAddProject: '添加项目上下文失败。', failedAddTeam: '添加团队上下文失败。', failedAddUser: '添加用户上下文失败。', failedRemoveContext: '移除上下文失败。', failedAddPage: '将此页面添加到 AI 上下文失败。',
  },
  audit: {
    pageTitle: '审计日志', noLogs: '未找到审计日志', time: '时间', action: '操作', entity: '实体', actor: '执行者', outcome: '结果', summary: '摘要', details: '审计日志详情', failedLoad: '加载审计日志失败。', inspect: '选择一条审计日志查看详情。', authentication: '身份验证', apiKey: 'API 密钥', teamJoinRequest: '团队加入请求', unavailableRecord: '记录不可用', unavailableProject: '项目不可用', unavailableUser: '不可用用户', system: '系统', changes: '更改', auditId: '审计 ID', success: '成功', failure: '失败', actionCreate: '创建', actionUpdate: '更新', actionDelete: '删除', actionLoginSuccess: '登录成功', actionLoginFailure: '登录失败',
  },
  subscriptions: {
    pageTitle: '订阅', empty: '暂无订阅', workItem: '工作项', subscribed: '订阅时间', action: '操作', unsubscribe: '取消订阅', unsubscribed: '已取消订阅“{{title}}”。', failedLoad: '加载订阅失败。', failedUnsubscribe: '取消订阅失败。', under: '位于',
  },
  myWork: {
    pageTitle: '我的工作', viewLabel: '我的工作视图', searchLabel: '搜索工作项', allProjects: '所有项目', allStatuses: '所有状态', allPriorities: '所有优先级', nothingAssigned: '没有分配给你的工作', noMatchingItems: '没有符合这些筛选条件的工作项', clearFilters: '清除筛选', workItem: '工作项', dueDate: '截止日期', overdue: '已逾期', noDueDate: '无截止日期', noPriority: '无优先级', updated: '更新时间', failedLoad: '加载分配给你的工作项失败。', boardEmpty: '暂无项目', showing: '显示', highPriority: '高优先级', list: '列表', grouped: '分组', board: '看板', filterProject: '按项目筛选', filterStatus: '按状态筛选', filterPriority: '按优先级筛选',
  },
  teams: {
    pageTitle: '团队', noTeams: '未找到团队', myRole: '我的角色', newTeam: '新建团队', teamOwners: '团队所有者', selectOwner: '选择所有者', addOwner: '添加团队所有者', removeOwner: '移除 {{name}} 的团队所有者身份', ownerRequired: '至少选择一名团队所有者。', nameRequired: '团队名称为必填项。', teamCreated: '团队已创建。', failedLoad: '加载团队失败。', failedCreate: '创建团队失败。', moreMembers: '另有 {{count}} 名成员', create: '创建',
  },
  teamDetails: {
    requestAccess: '申请访问', joinRequests: '加入请求', basicInfo: '基本信息', selectUser: '选择用户', selectProject: '选择项目', noOwners: '未分配所有者。', noMembers: '未分配成员。', noProjects: '未关联项目。', noRequests: '没有待处理的请求。', removeMember: '移除团队成员？', unlinkProject: '取消关联项目？', approve: '批准', reject: '拒绝', teamNotFound: '未找到团队。', failedLoad: '加载团队失败。', failedUpdate: '更新团队失败。', teamUpdated: '团队已更新。', failedDelete: '删除团队失败。', teamDeleted: '团队已删除。', memberAdded: '成员已添加。', failedAddMember: '添加成员失败。', memberRemoved: '成员已移除。', failedRemoveMember: '移除成员失败。', projectLinked: '项目已关联。', failedLinkProject: '关联项目失败。', projectUnlinked: '项目已取消关联。', failedUnlinkProject: '取消项目关联失败。', joinSubmitted: '加入请求已提交。', failedJoin: '申请加入团队失败。', joinApproved: '加入请求已批准。', joinRejected: '加入请求已拒绝。', failedJoinUpdate: '更新加入请求失败。', owners: '所有者', noRoleAssigned: '未分配{{role}}。', deleteTeam: '删除团队？', deleteTeamDescription: '团队成员关系和项目关联将被移除。', deleteTeamConfirm: '删除团队', removeMemberDescription: '该用户将失去通过此团队获得的访问权限。', removeMemberAction: '移除成员', unlinkProjectDescription: '该团队将失去通过此关联获得的项目访问权限。', unlink: '取消关联', unlinkProjectAction: '取消关联项目',
  },
  projects: {
    notDirect: '非直接访问', teamAccessUpdated: '团队访问权限已更新。', failedUpdateTeamAccess: '更新团队访问权限失败。',
    pageTitle: '项目', newProject: '新建项目', noProjects: '未找到项目', owners: '所有者', links: '关联', projectOwners: '项目所有者', moreOwners: '另有 {{count}} 名所有者', noOwners: '无所有者', workspace: '工作区', settings: '设置', projectMembers: '项目成员', assignedTeams: '已分配团队', selectUser: '选择用户', selectTeam: '选择团队', noDirectMembers: '未分配直接成员。', noTeams: '未分配团队。', selectProject: '选择一个项目查看详情。', removeMember: '移除项目成员？', removeTeam: '从项目中移除团队？', addOwner: '添加项目所有者', removeUserOwner: '移除用户所有者', removeTeamOwner: '移除团队所有者', teamOwner: '团队所有者', deleteProject: '删除项目？', nameRequired: '项目名称为必填项。', ownerRequired: '至少需要一名项目所有者。', projectCreated: '项目已创建。', projectUpdated: '项目已更新。', projectDeleted: '项目已删除。', failedLoad: '加载项目失败。', failedCreate: '创建项目失败。', failedUpdate: '更新项目失败。', failedDelete: '删除项目失败。', failedLoadAccess: '加载项目访问权限失败。', memberAdded: '项目成员已添加。', failedAddMember: '添加项目成员失败。', memberUpdated: '项目成员已更新。', failedUpdateMember: '更新项目成员失败。', memberRemoved: '项目成员已移除。', failedRemoveMember: '移除项目成员失败。', teamAssigned: '团队已分配。', failedAssignTeam: '分配团队失败。', teamRemoved: '团队已从项目中移除。', failedRemoveTeam: '移除团队失败。', editProject: '编辑项目', projectWorkspace: '项目工作区', openProject: '打开项目', assign: '分配', selectOwner: '选择所有者', createProject: '创建项目', deleteProjectButton: '删除项目', deletePermanently: '永久删除', noOwnersSelected: '尚未选择项目所有者。', removeMemberDescription: '该用户将失去此项目成员关系授予的直接访问权限。', removeMemberAction: '移除项目成员', removeTeamDescription: '团队成员将失去通过此团队获得的项目访问权限。', removeTeamAction: '移除团队', deleteProjectDescription: '这将永久删除项目工作区。',
  },
  projectSettings: {
    pageTitle: '项目', settings: '设置', projectNotFound: '未找到项目。', info: '信息', access: '访问权限', projectInfo: '项目信息', accessSummary: '访问摘要', accessByRole: '按角色查看访问权限', addAccess: '添加访问权限', yourAccess: '你的访问权限', noAccess: '未分配访问权限。', selectUser: '选择用户', selectTeam: '选择团队', removeMember: '移除项目成员？', removeTeam: '从项目中移除团队？', deleteProject: '删除项目？', deleteProjectDescription: '项目节点和访问权限分配将被移除。', removeMemberDescription: '该用户将失去此项目成员关系授予的直接访问权限。', removeTeamDescription: '团队成员将失去通过此团队获得的项目访问权限。', notDirect: '非直接访问', teamAccessUpdated: '团队访问权限已更新。', failedUpdateTeamAccess: '更新团队访问权限失败。',
  },
  usersPage: {
    pageTitle: '用户', newUser: '新建用户', editUser: '编辑用户', userDetails: '用户详情', noUsers: '未找到用户', noTimezone: '未找到时区。', displayName: '显示名称', bio: '简介', passwordResetRequired: '需要重置密码', security: '安全', temporaryPassword: '临时密码', initialPassword: '初始密码', requirePasswordUpdate: '要求用户下次登录时更新密码', resetPassword: '重置密码', resetting: '重置中…', selectUser: '选择一个用户查看详情。', emailInvalid: '请输入有效的邮箱地址。', userCreated: '用户已创建。', userUpdated: '用户已更新。', userDeleted: '用户已删除。', passwordReset: '密码已成功重置。', failedLoad: '加载用户失败。', failedLoadDetails: '加载用户详情失败。', failedSave: '保存用户失败。', failedDelete: '删除用户失败。', failedReset: '重置密码失败。', deleteUser: '删除用户？', createUser: '创建用户', deleteUserDescription: '这将停用用户账户、移除其项目和团队成员关系，并立即将其退出登录。历史活动仍会保留其姓名。', deleteUserConfirm: '删除用户', deleteUserButton: '删除用户',
  },
  account: {
    audioTranscription: '语音转写',
    passwordUpdated: '密码已更新。',
    apiKeysDescription: '为 CLI 和外部集成创建密钥。每个密钥仅拥有你选择的权限。',
    permissions: '权限',
    permissionCount: '{{count}} 项权限',
    pageTitle: '我的账户', profile: '个人资料', password: '密码', apiKeys: 'API 密钥', system: '系统', noUser: '当前没有可用的已认证用户。', updatePasswordRequired: '需要更新密码', updatePasswordDescription: '请设置新密码后再继续。', serverVersion: '服务器版本', systemUnavailable: '系统信息不可用。', newKey: '新密钥', keyName: '密钥名称', scopes: '权限范围', total: '共 {{count}} 个', shownOnce: '只显示一次。离开此页面前请妥善保存。', noKeys: '尚未创建 API 密钥。', createKeyHint: '在上方创建一个密钥即可开始。', lastUsed: '最后使用', revokeKey: '撤销 API 密钥？', keyNameRequired: 'API 密钥名称为必填项。', scopeRequired: '至少选择一个权限范围。', keyCreated: 'API 密钥已创建。', keyCopied: 'API 密钥已复制。', keyRevoked: 'API 密钥已撤销。', failedLoadKeys: '加载 API 密钥失败。', failedLoadSystem: '加载系统信息失败。', failedLoadUser: '加载用户信息失败。', failedCreateKey: '创建 API 密钥失败。', failedRevokeKey: '撤销 API 密钥失败。', currentPasswordRequired: '当前密码为必填项。', newPasswordRequired: '新密码为必填项。', failedUpdatePassword: '更新密码失败。', signOut: '退出登录', signingOut: '退出中…', account: '账户', passwordRequired: '需要密码', currentPassword: '当前密码', systemInformation: '系统信息', llmProvider: 'LLM 提供商', available: '可用', unavailable: '不可用', refreshing: '刷新中…', scopesSelected: '已选择 {{selected}}/{{total}}', selectAll: '全选', creating: '创建中…', createApiKey: '创建 API 密钥', copy: '复制', existingKeys: '现有密钥', revokeDescription: '此密钥将立即停止工作。', revoke: '撤销', revoking: '撤销中…', scopeGroups: { teams: '团队', users: '用户', projects: '项目', workItems: '工作项', entries: '条目', relationships: '关系', audit: '审计' }, scopeOptions: { teamsReadLabel: '读取团队', teamsReadDescription: '读取外部 API 中的团队。', teamsWriteLabel: '写入团队', teamsWriteDescription: '创建、更新和删除团队。', teamMembersReadLabel: '读取成员', teamMembersReadDescription: '读取团队成员列表。', teamMembersWriteLabel: '写入成员', teamMembersWriteDescription: '添加和移除团队成员。', teamProjectsReadLabel: '读取项目', teamProjectsReadDescription: '读取与团队关联的项目。', usersReadLabel: '解析用户', usersReadDescription: '通过用户 ID 解析有限的身份信息。', projectsReadLabel: '读取项目', projectsReadDescription: '读取密钥所有者可见的项目。', projectsWriteLabel: '写入项目', projectsWriteDescription: '创建项目并更新自己拥有的项目。', projectAccessReadLabel: '读取访问权限', projectAccessReadDescription: '读取项目成员和已分配的团队。', projectAccessWriteLabel: '写入访问权限', projectAccessWriteDescription: '管理项目成员和已分配的团队。', workItemsReadLabel: '读取工作项', workItemsReadDescription: '读取结构化工作项及其大纲。', workItemsWriteLabel: '写入工作项', workItemsWriteDescription: '创建、更新、移动和删除工作项。', entriesReadLabel: '读取条目', entriesReadDescription: '读取评论、回答、证据和其他条目。', entriesWriteLabel: '写入条目', entriesWriteDescription: '创建、更新和删除条目。', relationshipsReadLabel: '读取关系', relationshipsReadDescription: '读取依赖、阻塞、回答和其他语义关系。', relationshipsWriteLabel: '写入关系', relationshipsWriteDescription: '创建和删除语义关系。', auditLogsReadLabel: '读取审计日志', auditLogsReadDescription: '读取全局或项目审计日志。' },
  },
  analytics: {
    pageTitle: 'AI 分析', allProjects: '所有项目', allTime: '全部时间', lastDays: '最近 {{count}} 天', refresh: '刷新', unavailable: 'AI 提供商不可用，但历史分析仍可查看。', overview: '概览', usageReliability: '使用量与可靠性', roiOutcomes: 'ROI 与结果', usageByFeature: '按功能查看 AI 使用量', noFeatureUsage: '暂无功能使用数据', feature: '功能', featureChat: '聊天', featureEntryAiReview: '条目 AI 审核', featureWorkItemAiReview: '工作项 AI 审核', timeSavedEstimate: '时间节省如何估算', timeSavedAssumptions: '时间节省假设', estimatedMinutes: '每个已接受更改预计节省的分钟数。', minutes: '{{value}} 分钟', acrossAccepted: '共 {{count}} 个已接受的更改', changesAccepted: '已接受的更改', nodesEdges: '{{nodes}} 个节点，{{edges}} 条边', decidedChanges: '{{count}} 个已决定的更改', rework: '返工', rejectedNeedsUpdate: '{{rejected}} 个已拒绝，{{needsUpdate}} 个需要更新', noImpact: '暂无 AI 影响数据', saved: '节省', accepted: '已接受', pending: '待处理', rate: '比率', tokenUsage: '令牌使用量', failed: '{{count}} 次失败', ofRequests: '共 {{count}} 个请求', perRequest: '每个请求', noTokenUsage: '暂无令牌使用数据', avgLatency: '平均延迟', unknownProject: '未知项目', models: '模型', provider: '提供商', model: '模型', failedLoadTokens: '加载令牌使用量失败。', failedLoadReport: '加载 AI 分析报告失败。', aiRequests: 'AI 请求', loadingUsage: '正在加载使用量', totalTokens: '令牌总数', inputOutput: '输入 + 输出', loadingOutcomes: '正在加载结果', acceptanceRate: '接受率', estimatedTimeSaved: '预计节省时间', reworkRequested: '请求返工', inputOutputValues: '输入 {{input}} · 输出 {{output}}', nodeAdd: '添加节点', nodeUpdate: '更新节点', nodeDelete: '删除节点', edgeAdd: '添加边', edgeUpdate: '更新边', edgeDelete: '删除边',
  },
  history: {
    noHistory: '暂无历史记录', failedLoad: '加载历史记录失败。', justNow: '刚刚', minutesAgo: '{{count}} 分钟前', hoursAgo: '{{count}} 小时前', daysAgo: '{{count}} 天前', metadata: '元数据', before: '之前', after: '之后',
  },
  workspace: {
    changesAcceptedWithPending: '可用更改已接受。等待其他建议项目的关系仍处于待处理状态。', empty: '空', parentOutsideTree: '父项目不在已加载的树中', topLevelOutsideTree: '顶层项目提案不在已加载的树中', targetOutsideTree: '目标项目不在已加载的树中',
    untitledItem: '未命名项目', untitledUpdate: '未命名更新', update: '更新',
    acceptedAnswerUpdated: '已接受的回答已更新。', failedRefreshBlockers: '刷新阻塞项失败。', failedAddBlocker: '添加阻塞项失败。', failedRemoveBlocker: '移除阻塞项失败。', failedUpdateBlockerReason: '更新阻塞原因失败。', failedAddRelationship: '添加关系失败。', failedRemoveRelationship: '移除关系失败。', suggestionAccepted: 'AI 建议已接受。', suggestionRejected: 'AI 建议已拒绝。', failedRunFilters: '运行工作项筛选失败。', failedClearFilters: '清除工作项筛选失败。', failedSort: '排序工作项失败。', failedUpdateSubscription: '更新订阅失败。', failedLoadSubItems: '加载子项目失败。', expandedFirst: '已展开前 {{count}} 个嵌套项目。折叠并重新打开分支可加载更多。', failedExpandSubItems: '展开子项目失败。', failedLoadMore: '加载更多项目失败。', failedLoadMoreSubItems: '加载更多子项目失败。', blockersAdded: '已添加 {{count}} 个阻塞项。', failedAddSuggestedBlockers: '添加建议的阻塞项失败。', nestedItem: '嵌套项目', projectLevel: '项目层级', updateAction: '更新', loadMoreRoots: '加载更多根项目',
    blockedBy: '阻塞于', askQuestion: '提问', fields: '字段', entries: '条目', proposalDecisionFailed: '{{decision}} AI 建议失败。', backToProjects: '返回项目', filters: '筛选', conditionOperator: '条件运算符', assignee: '负责人', assigneesTooltip: '负责人：{{assignees}}', addCondition: '添加条件', runFilters: '运行筛选', created: '创建时间', addSubItem: '添加子项目', newItem: '新建项目', task: '任务', exitFocus: '退出聚焦', details: '详情', history: '历史记录', noAssigneesAvailable: '没有可用的{{type}}', selectAssigneeType: '选择{{type}}', removeAssignee: '移除负责人', unsaved: '未保存', saved: '已保存', choosePlacement: '选择将 {{title}} 放置在何处。', chooseThisPlacement: '选择将此项目放置在何处。', endOfProjectLevel: '项目层级末尾', classification: '分类', added: '已添加', removed: '已移除', changed: '已更改', actionAdd: '添加', actionUpdate: '更新', actionDelete: '删除',
    acceptDeleteProposal: '接受删除提案', acceptProposal: '接受提案', acceptSuggestionButton: '接受建议', actionsFor: '{{title}} 的操作', addBlocker: '添加阻塞项', addReason: '添加原因', addRelationship: '添加关系', addTask: '添加任务', aiProposed: 'AI 提案', aiReview: 'AI 审核', applyPermanentDeletion: '应用永久删除？', blockersCount: '查看并管理 {{count}} 个阻塞项', cancelTitleEdit: '取消标题编辑', change: '项更改', changes: '{{count}} 项更改', collapseItem: '折叠项目', deleteItemDescription: '该项目的子项目也将被删除。', deleteSuggestionDescription: '此 AI 建议将永久删除该项目及其子项目。', deleteSuggestionRecords: '此 AI 建议将永久删除一条或多条记录。', deleteUpdateDescription: '此更新将被永久删除。', direction: '方向', due: '截止日期：{{date}}', editTitle: '编辑标题', editUpdate: '编辑更新', existingWorkItem: '现有工作项', expandItem: '展开项目', failedAcceptAnswer: '接受回答失败。', failedAcceptSuggestion: '接受 AI 建议失败。', failedRejectSuggestion: '拒绝 AI 建议失败。', failedSuggestionUpdate: '更新 AI 建议失败。', failedUpdateTitle: '更新项目标题失败。', focus: '聚焦', hideUpdates: '隐藏更新（{{count}}）', itemTitleRequired: '工作项标题为必填项。', loadMoreSubItems: '加载更多', loadingSubItems: '正在加载子项目', manageBlockers: '管理阻塞项', moreAssignees: '另有 {{count}} 名负责人', move: '移动', moveDown: '下移', moveUp: '上移', new: '新', noAvailableWorkItems: '没有可用工作项', noChangedFields: '未检测到更改的字段。', old: '旧', optional: '可选', parent: '父级', projectRoot: '项目根节点', proposedNewWorkItem: '建议的新工作项', proposedUpdate: '建议的更新', proposedValuesUnavailable: '此提案没有可用的新值。', reason: '原因', rejectProposal: '拒绝提案', removeBlocker: '移除阻塞项', requestApproval: '请求批准', reviewDetailsBeforeAdding: '添加到工作区前请查看详情。', reviewOldNewValues: '接受前请查看旧值和新值。', saveTitle: '保存标题', searchWorkItems: '搜索工作项', selectedToThisItem: '选中项目 → 此项目', showUpdates: '显示更新（{{count}}）', thisItemToSelected: '此项目 → 选中项目', viewBlockers: '查看并管理阻塞项', writeAnswer: '写入回答…', writeUpdate: '写入更新…',
    pageTitle: '项目', projectNotFound: '未找到项目', projectSettings: '项目设置', filterWorkItems: '筛选工作项', conditions: '条件', where: '条件字段', and: '且', or: '或', overdue: '已逾期', dueToday: '今天到期', next7Days: '未来 7 天', selectAssignee: '选择负责人', removeCondition: '移除筛选条件', oldestFirst: '创建时间：最早优先', newestFirst: '创建时间：最新优先', showInspector: '显示检查器', hideInspector: '隐藏检查器', focused: '当前聚焦：', noItems: '暂无项目', pendingProposals: '加载树之外的待处理提案', inspectorMode: '检查器模式', expandAll: '全部展开', expandAllHelp: '加载并展开所有嵌套工作项', collapse: '折叠', collapseHelp: '折叠此项及其所有嵌套工作项', stopSubscription: '停止接收此工作项的更新', subscribe: '订阅此工作项的更新', aiSuggestion: 'AI 建议', suggestedBlockers: '建议的阻塞项', askAgain: '再次询问', applyToDraft: '应用到草稿', addSuggestedBlockers: '添加建议的阻塞项', noAssignees: '暂无负责人。', relationships: '关系', removeRelationship: '移除关系', removeRelationshipWith: '移除与 {{title}} 的关系', itemActions: '工作项操作', deleteItem: '删除工作项？', updateContent: '更新内容', yourDraft: '你的草稿', suggested: '建议', keepEditing: '继续编辑', selectItem: '选择一个工作项或更新', moveItem: '移动工作项', moveBefore: '移动到此项之前', noPlacementTargets: '没有有效的放置目标', titleRequired: '工作项类型和标题为必填项。', fieldNameRequired: '每个字段都需要名称。', uniqueFieldNames: '字段名称必须唯一。', invalidNumber: '字段“{{field}}”必须是有效数字。', acceptRejectFromRow: '请在树行中接受或拒绝此提案。', proposalUnavailable: '提案更改已不可用。', acceptItemsFirst: '请先接受建议的工作项，再接受此关系。', failedLoadProject: '加载项目失败。', failedCreateItem: '创建工作项失败。', failedUpdateItem: '更新工作项失败。', failedDeleteItem: '删除工作项失败。', failedMoveItem: '移动工作项失败。', failedReorder: '重新排序内容失败。', failedSuggestion: '获取 AI 建议失败。', failedRefreshSuggestions: '刷新 AI 建议失败。', saveSuggestion: 'AI 建议已应用到草稿。保存更改即可更新工作项。', itemCreated: '工作项已创建。', subItemCreated: '子工作项已创建。', itemUpdated: '工作项已更新。', itemDeleted: '工作项已删除。', itemMoved: '工作项已移动。', itemMovedToEnd: '工作项已移动到项目层级末尾。', updateSaved: '更新已保存。', updateRequired: '更新文本为必填项。', failedReviewUpdate: '审核更新失败。', failedAddUpdate: '添加更新失败。', failedSaveUpdate: '保存更新失败。', updateActions: '更新操作', deleteUpdate: '删除更新？', tellAi: '告诉 AI 要更改什么…', acceptAnswer: '接受回答', acceptSuggestion: '接受 AI 建议', rejectSuggestion: '拒绝 AI 建议', keepEditingSuggestion: '继续编辑 AI 建议', updateClassification: '更新分类', addUpdate: '添加更新', cancelNewUpdate: '取消新更新', blockerAdded: '阻塞项已添加。', blockerRemoved: '阻塞项已移除。', blockerReasonUpdated: '阻塞原因已更新。', blockerReasonRemoved: '阻塞原因已移除。', relationshipAdded: '关系已添加。', relationshipRemoved: '关系已移除。', subscriptionUpdated: '订阅已更新。', subscribed: '已订阅此工作项。', unsubscribed: '已取消订阅此工作项。',
  },
  notifications: { title: '通知', open: '打开', secondsAgo: '{{count}} 秒前', minutesAgo: '{{count}} 分钟前', hoursAgo: '{{count}} 小时前', daysAgo: '{{count}} 天前', unread: '{{count}} 条未读通知', markAllRead: '全部标为已读', caughtUp: '你已经看完所有通知。' },
  pane: { openAskAi: '打开 Ask AI', expandAskAi: '展开 Ask AI', workspacePanes: '工作区面板', chat: '聊天', artifact: '内容', collapseConversation: '折叠对话' },
  navigation: {
    home: '首页',
    newChat: '新建聊天',
    search: '搜索',
    recentConversations: '最近对话',
    workspace: '工作区',
    projects: '项目',
    myWork: '我的工作',
    subscriptions: '订阅',
    teams: '团队',
    users: '用户',
    administration: '管理',
    auditLogs: '审计日志',
    aiAnalytics: 'AI 分析',
  },
  language: {
    label: '语言',
    preferencesTitle: '语言偏好',
    description: '选择界面语言。',
  },
} as const
export default zh
